SinemaAppWeb/Models/Category.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SinemaAppWeb.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

SinemaAppWeb/Models/Movie.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SinemaAppWeb.Models
{
    public class Movie
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="Film adı alanı boş bırakılamaz!")]
        [StringLength(50, ErrorMessage = "Film adı 50 karakterden uzun olamaz!")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Açıklama alanı boş bırakılamaz!")]
        public string Description { get; set; }
        public string IMDbStar { get; set; }
        public string Yonetmen { get; set; }
        public string Oyuncular { get; set; }
        [Required(ErrorMessage = "Fotoğraf alanı boş bırakılamaz!")]
        public string ImageUrl { get; set; }

        public string TrailerUrl { get; set; }

        public int CategoryId { get; set; }
    }
}

SinemaAppWeb/Models/MovieCategoryModel.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SinemaAppWeb.Models
{
    public class MovieCategoryModel
    {
        public Movie Movie { get; set; }
        public IEnumerable<Movie> Movies { get; set; }
        public IEnumerable<Category> Categories { get; set; }
    }
}

SinemaAppWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using SinemaAppWeb.Data;
using SinemaAppWeb.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SinemaAppWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index(int? id)
        {
            var movies = MovieRepository.Movies;
            if (id!=null)
            {
                movies = movies.Where(i => i.CategoryId == id).ToList();
            }
            return View(movies);
        }

        public IActionResult Details(int id)
        {
            
            return View(MovieRepository.GetById(id));
        }
        

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(CategoryRepository.Categories, "Id", "Name");
            return View();
        }

       [HttpPost]
        public IActionResult Create(Movie m)
        {
            if (ModelState.IsValid)
            {
                MovieRepository.AddMovie(m);
                return RedirectToAction("index");
            }
            
            return View(m);
        }
       
    }
}

SinemaAppWeb/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SinemaAppWeb.Controllers
{
    public class MovieController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult List()
        {
            return View();
        }
        public IActionResult Details()
        {
            return View();
        }

    }
}

SinemaAppWeb/ViewComponents/CategoryMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SinemaAppWeb.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SinemaAppWeb.ViewComponents
{
    public class CategoryMenuViewComponent: ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            if (RouteData.Values["action"].ToString()=="Index")
            {
                    ViewBag.SelectedCategory = RouteData?.Values["id"];
            }
            
            return View(CategoryRepository.Categories);
        }
    }
}

SinemaAppWeb/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h1>@ViewData["Title"]</h1>

SinemaAppWeb/Views/Home/Create.cshtml
@model Movie

    <div class="container mx-4 my-4">
        <br />
        <form method="POST">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label for="Name">Film Adı</label>
                <input asp-for="Name" class="form-control" placeholder="Film Adı">
            </div>
             <div class="form-group">
                <label for="IMDbStar">Film IMDb ID'si</label>
                <input asp-for="Name" class="form-control" placeholder="Film IMDb ID'si">
            </div>
            <div class="form-group">
                <label for="Description">Açıklama</label>
                <textarea asp-for="Description" class="form-control" placeholder="Açıklama"></textarea>
            </div>
            <div class="form-group">
                <label for="Name">Yönetmen</label>
                <input asp-for="Yonetmen" class="form-control" placeholder="Yönetmen">
            </div>
            <div class="form-group">
                <label for="Oyuncular">Oyuncular</label>
                <input asp-for="Oyuncular" class="form-control" placeholder="Oyuncular">
            </div>
            <div class="form-group">
                <label for="ImageUrl">Film Afişi</label>
                <input asp-for="ImageUrl" class="form-control" placeholder="Örn: 1.jpg">
            </div>
             <div class="form-group">
                <label for="TrailerUrl">Film Fragmanı</label>
                <input asp-for="TrailerUrl" class="form-control" placeholder="Film Fragmanı">
            </div>
            <div class="form-group">
                <label for="CategoryId">Kategori</label>
                <select asp-for="CategoryId" asp-items="@ViewBag.Categories" class="form-control">
                    <option selected disabled>Seçiniz</option>
                </select>
            </div>
            <button type="submit" class="btn btn-block btn-warning">Ekle</button>
            <br />
            <br />
        </form>
    </div>

SinemaAppWeb/Views/Home/Details.cshtml
@model Movie


<div class="row mb-5">
    <div class="col-md-12">


        <div class="card mb-3">
            <div class="card-body">
                <div class="row no-gutters"> 
                        <div class="col-md-4" >
                            <img src="@Model.ImageUrl" alt="@Model.Description" class="card-img" style="border: 3px solid #09e3e5;width:auto;height:475px"/>
                        </div>
                        <div class="trailer">
                            <iframe width="634" height="475" src="@Model.TrailerUrl" title="YouTube video player" style="border: 3px solid #09e3e5;" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                        </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h3 class="card-title" style="color:#09e3e5;">
                                <b>@Model.Name</b>
                            </h3>
                            <p class="card-text">@Model.Description</p>
                            <br />
                            <p class="card-text"><b style="font-size: 20px; color:#09e3e5">Yönetmen: </b>@Model.Yonetmen</p>
                            <br />
                            <p class="card-text"><b style="font-size: 20px; color:#09e3e5">Oyuncular: </b>@Model.Oyuncular</p>
                            <br />
                        </div>
                    </div>
                </div>
            </div>


        </div>
        <br />
        <a href="/home/index">Ana menüye dön</a>
        <br />
        <br />
        <br />
    </div>

    


</div>

SinemaAppWeb/Views/Home/Index.cshtml
@model IEnumerable<Movie>



<div class="row">
    <div class="col-md-10">
        @Html.Partial("_movies", Model)
        
    </div>
    <div class="col-md-2">
        @await Component.InvokeAsync("CategoryMenu")
    </div>

    
</div>

SinemaAppWeb/Views/Home/_movies.cshtml
@model IEnumerable<Movie>

@foreach (var item in Model)
{
    <div class="card mb-3">
        <div class="row no-gutters">
            <div class="col-md-3">
                <a asp-action="Details" asp-controller="Home" asp-route-id="@item.Id"><img src="@item.ImageUrl" alt="@item.Description" class="card-img" /></a>
            </div>
            <div class="col-md-9">
                <div class="card-body">
                    <h4 class="card-title">
                        <a asp-action="Details" asp-controller="Home" asp-route-id="@item.Id">@item.Name</a>
                    </h4>
                    <p class="card-text">@item.Description</p>
                    <div class="imdb">
                        <span class="imdbRatingPlugin" style="float:right;" data-user="ur80028027" data-title="@item.IMDbStar" data-style="p1"><a href="https://www.imdb.com/title/@item.IMDbStar/?ref_=plg_rt_1"><img src="https://ia.media-imdb.com/images/G/01/imdb/plugins/rating/images/imdb_46x22.png" alt=" @item.Name" /></a></span><script>(function(d,s,id){var js,stags=d.getElementsByTagName(s)[0];if(d.getElementById(id)){return;}js=d.createElement(s);js.id=id;js.src="https://ia.media-imdb.com/images/G/01/imdb/plugins/rating/js/rating.js";stags.parentNode.insertBefore(js,stags);})(document,"script","imdb-rating-api");</script>                   
                        <a asp-action="Details" asp-controller="Home" asp-route-id="@item.Id" class="btn-sm  float-left" style="text-decoration:none; background-color: #09e3e5; color: #000000;"><b>Detaylar</b></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

SinemaAppWeb/Views/Movie/Details.cshtml
<h1>movie/details</h1>

SinemaAppWeb/Views/Movie/Index.cshtml
<h1>Movie/Index</h1>

SinemaAppWeb/Views/Movie/List.cshtml
<h1>movie/list</h1>

SinemaAppWeb/Views/Shared/Components/CategoryMenu/Default.cshtml
@model IEnumerable<Category>

<div class="list-group">
    <a href="/home/index" class="list-group-item list-group-item-action">Tüm Kategoriler</a>
    @foreach (var i in Model)
    {
        <a asp-action="Index" asp-controller="Home" asp-route-id="@i.Id" class="list-group-item list-group-item-action @(ViewBag.SelectedCategory==i.Id.ToString()?"activated":"")">@i.Name</a>
    }


</div>

SinemaAppWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="icon" type="image/x-icon" href="~/favicon.ico" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
    <title>Sinefil</title>
</head>
<body>
    <header>
        @Html.Partial("_navbar")
    </header>
    <main>
        <div class="container mt-4">
            @RenderBody()
        </div>
    </main>
    <footer>
        @Html.Partial("_footer")
    </footer>
        
    
</body>
</html>

SinemaAppWeb/Views/Shared/_footer.cshtml
<div class="footer py-3 mt-3">
    <div class="container">
    </div>
</div>

SinemaAppWeb/Views/Shared/_menu.cshtml
@model IEnumerable<Category>

<div class="list-group">

    @foreach (var i in Model)
	{
        <a href="#" class="list-group-item list-group-item-action">@i.Name</a>
	}
    <a href="#" class="list-group-item list-group-item-action activated">content1</a>
    
</div>

SinemaAppWeb/Views/Shared/_navbar.cshtml
<div class="navbar navbar-expand-sm bg-warning navbar-dark" style="background-color:white !important;">
    <div class="container">
        <a href="/home/index"><img src="~/img/SİNEFİL.png" style="width:299px;height:73px;display: block;margin-left: 150%;margin-right: auto;"></a>
        <ul class="navbar-nav" style="color:aqua !important;">
            <li class="nav-item">
                <a href="/home/index" class="nav-link"><img src="~/img/Tüm Filmler.png"></a>
            </li>
            <li class="nav-item">
                <a href="/home/create" class="nav-link"><img src="~/img/Film Ekle.png"></a>
            </li>
        </ul>
    </div>
</div>